### ISSUE TITLE
Case sensitive file name

### ISSUE THREAD

**Issue by tathanhdinh** [JerreS/AsmResolver#11]
Hi and many thanks for this project, 
I have built AsmResolver on Windows without any problem, but on Linux (with Mono), there are two minor errors concerning the file naming difference between Linux (case sensitive) and Windows (case insensitive). They come from two files: [MetaDataToken.cs](https://github.com/JerreS/AsmResolver/blob/master/AsmResolver/Net/Metadata/MetaDataToken.cs) and [MetaDataStreamHeader.cs](https://github.com/JerreS/AsmResolver/blob/master/AsmResolver/Net/MetaDataStreamHeader.cs) which should be renamed to `MetadataToken.cs` and `MetadataStreamHeader.cs`.

**Comment by JerreS** [comment]
Hi,

Thanks for the catch. I updated the file names.

Regards

**Comment by tathanhdinh** [comment]
Hi JerreS,
Thanks for this very quick response.
Best regards.
