### ISSUE TITLE
Change license to LGPL instead of GPL

### ISSUE THREAD

**Issue by duncanisgoed** [JerreS/AsmResolver#8]
When using this library I might not want to make my code that uses it open source. Please consider using LGPL. This way changes to your library will be sent back to you, but people are not forced to make their tools open source as well.

**Comment by JerreS** [comment]
Hello duncanisgoed,

I have reviewed the LGPL license and I agree this license would indeed be more suitable for this project than the GPL license is. Thanks for the catch, I will change it.

Regards
