### ISSUE TITLE
Troubles with filling IList<ImageSymbolExport> Exports in ImageExportDirectory.cs

### ISSUE THREAD

**Issue by bybarks** [JerreS/AsmResolver#9]
Troubles arise while working with dll having ordinals exports and mixed ordinals and named.

1) If only ordinals in dll then AddressOfNameOrdinals and AddressOfNames both are equal to 0 and  code below gives exceptions (ArgumentOutOfRangeException("rva") leaving Exports property empty.

application.RvaToFileOffset(AddressOfNameOrdinals); 
application.RvaToFileOffset(AddressOfNames);

2) If mixed "ordinals and named export functions" the
                 for (int i = 0; i < NumberOfFunctions; i++) {} cycle
gives wrong results. The first ordinal gets name of first named function and then exception after (NumberOfNames)-times.
We must skip reading nameReader.ReadAsciiString()  (NumberOfFunctions-NumberOfNames)-times.
AFAIK, NumberOfFunctions - is a total number of exported functions, including NumberOfNames.
I didn't look at standard but as it's in mfcm90.dll named functions go after ordinals.

3) Examples of such dlls are mfc90.dll and mfcm90.dll

**Comment by JerreS** [comment]
Hi bybarks,

Thanks for finding and reporting the bug. I also believe the unnamed entries are followed by the named symbols. I have revisited the chapter about the exports directory in the official Microsoft Portable Executable and Common Object File Format Specification (rev. 8.3), but could not find a confirmation for this. It is possible that I have misread it, as English is not my native language. I have, however, opened your suggested libraries (mfc90.dll and mfcm90.dll) and several others (such as ntdll.dll) whose export directory consists of both unnamed and named exports, and could only find more evidence that confirms this conjecture. Therefore, I think it is safe to add a couple of checks to the loop. I will commit the changes asap.

Regards

**Comment by bybarks** [comment]
Hi, JerreS,
So am I. English isn't my native.
So am I, I  could not find a confirmation of sequencing of unnamed and named symbols.
1) But if they mixed up we have not any information on what type of symbol we are dealing.
2) mfcm90.dll - shows us suggestion.

3) My piece of code (still :) ) works
 (even with ordinals with AddressOfFunctions=0 in mixed symbols mode).
You may use my snippet. You may do better :) in your.

<<<<<<<<<< start of snippet
                var addressReader = reader.CreateSubReader(application.RvaToFileOffset(AddressOfFunctions));
                IBinaryStreamReader nameOrdinalReader = null;
                IBinaryStreamReader nameRvaReader = null;
                uint iNamedFunctionsOffset = NumberOfFunctions;
                if (NumberOfNames != 0)
                {   // if there are a named information - get their subreaders
                    nameOrdinalReader = reader.CreateSubReader(application.RvaToFileOffset(AddressOfNameOrdinals));
                    nameRvaReader = reader.CreateSubReader(application.RvaToFileOffset(AddressOfNames));
                    iNamedFunctionsOffset -= NumberOfNames;
                }

                for (int i = 0; i < NumberOfFunctions; i++)
                {
                    UInt32 uRva = addressReader.ReadUInt32();
                    if (uRva == 0) continue;    // skip (not necessarily) (no code/data is exported with that ordinal value)(or we can create export entry with 0-address, to get information "as is")

                    var export = new ImageSymbolExport()
                    {
                        Rva = uRva,
                        NameOrdinal = (ushort)(i + OrdinalBase)  // besides I biased ordinal numbers (not necessarily)
                    };
                    
                    if(i>=iNamedFunctionsOffset)
                    {   // reached named symbols
                        export.NameOrdinal = (ushort)(nameOrdinalReader.ReadUInt16()  + OrdinalBase);
                        export.NameRva = nameRvaReader.ReadUInt32();
                        var nameReader = reader.CreateSubReader(application.RvaToFileOffset(export.NameRva));
                        export.Name = nameReader.ReadAsciiString();
                    }

                    // TODO: set IsForwarder and ForwarderName properties.

                    _exports.Add(export);
                }
<<<<<<<<<<<<<<< end of snippet

**Comment by bybarks** [comment]
Hi, Jerres,
I could be misaken, but using only next code:

                    if (i >= NumberOfFunctions - NumberOfNames)
                    {
                        if (nameOrdinalReader != null)
                            export.NameOrdinal = nameOrdinalReader.ReadUInt16();

export.NameOrdinal would be 0 for all ordinals (but has value only for named), but it would be equal 'i' ?
You miss line:
NameOrdinal = (ushort) i

in construction before

 var export = new ImageSymbolExport()
     {}

are you?

**Comment by JerreS** [comment]
Hi bybarks,

First of all, sorry for the late reply, I had other business to do. 

It seems it is a little bit more complicated, but I think I have cracked it. The names are associated with the exported symbol based on their ordinal. The exported symbols do always have an RVA and an ordinal, like you said in your reply. However, not all unnamed symbols are necessarily preceding the named ones. A symbol is named when its ordinal is present in the what I like to call the *Ordinal-NameRva* table, two sets of arrays with *NumberOfNamed* amount of elements at address *AddressOfNameOrdinals* and *AddressOfNames*. If the ordinal exists in the table, a Name Rva also exists, and therefore a name can be assigned to the exported symbol.

Thanks again for pointing out the bug ;)

Regards,

**Comment by bybarks** [comment]
Hi, JerreS!
I revised the code and it's seems like a well done. Your code is more universal and  independent from a misunderstanding of the PE-specification than my one.

Thanks for you job, JerreS.
Good luck!
